fix image src, add release steps and more badges
bluehost/bluehost-wordpress-plugin pull request #173
Opened 2022-07-28 19:54 UTC by circlecube

## Proposed changes

This adds the steps we discussed today to a quick list on the main plugin readme file. Should be easy to follow them for releases in the future. I tried to add any relevant links to point future us in the right direction in case we run into any issues. Please read through them to make sure I didn't forget anything.

I also updated the logo image since the old one was broken and added more badges so we can better see status of the latest build, lint and tests.

The only issue I see is that in an .md file like this, the checkboxes are not interactive, so not much point in having them here. It was a nice thought though.

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2022-07-28 20:19 UTC, aalani95 approved these changes
Perfect. Approved!

2022-07-28 20:21 UTC, aalani95 approved these changes

2022-07-29 19:33 UTC, wpscholar requested changes
We should update the URL reference since we'll be getting that updated shortly.

2022-07-29 19:33 UTC, wpscholar commented on README.md
> +- [ ] Ensure [cloudflare worker](https://wp-github-release-api.bluehost.workers.dev/plugins/bluehost/bluehost-wordpress-plugin) displays the release as latest/current version.
```suggestion
- [ ] Ensure [cloudflare worker](https://hiive.cloud/workers/release-api/plugins/bluehost/bluehost-wordpress-plugin/) displays the release as latest/current version.
```

2022-07-29 19:33 UTC, wpscholar commented on README.md
> +- [ ] Watch for plugin release rollout in hiive.
```suggestion
- [ ] Watch for plugin release rollout in Hiive.
```

2022-07-29 20:22 UTC, merged